import { StyleSheet } from "react-native";
import {heightPercentageToDP as hp, widthPercentageToDP as wp} from 'react-native-responsive-screen';

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#B4D2E7',
        alignItems: 'center',
        justifyContent: 'center',
    },
    CoverText: {
        top: hp(0),
        width: wp(100),
        height: hp(20),
        borderRadius: hp(5),
        alignContent: 'center',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: '#407eea',
        marginBottom: hp(-3),
    },
    snowSpot: {
        top: hp(3),
        color: '#B4D2E7',
        fontFamily: "GillSans-Light",
        fontSize: hp(3),
        fontWeight: '500',
        marginBottom: hp(1),
    },
    postView: {
        flex: 1,
        top: hp(5),
    },
    buttonPost: {
        marginTop: hp(2),
        top: hp(2),
        backgroundColor: '#ffffff',
        padding: hp(2),
        width: wp(50),
        borderRadius: hp(5),
    },
    postText: {
        color: '#023CAA',
        fontFamily: "GillSans-Light",
        fontSize: hp(2.25),
        textAlign: 'center',
        fontWeight: '500'
    },
    bottomBar: {
        backgroundColor: '#407eea',
        width: wp(100),
        height: hp(10),
        borderRadius: hp(5),
    },
    profileBox: {
        width: hp(8),
        height: hp(8),
        top: hp(1),
        left: hp(4),
        marginBottom: hp(2),
        borderRadius: hp(5),
        backgroundColor: '#B4D2E7',
    },
    profileBoxInitials: {
        fontFamily: "GillSans-Light",
        fontWeight: '500',
        fontSize: hp(2.75),
        alignSelf: 'center',
        allignText: 'center',
        justifyContent: 'center',
        top: hp(2.25),
    },
    settingsBox: {
        width: hp(8),
        height: hp(8),
        top: hp(-9),
        left: hp(35),
        marginBottom: hp(2),
        borderRadius: hp(5),
        backgroundColor: '#B4D2E7',
    },
    gearEmoji: {
        fontSize: hp(5),
        alignSelf: 'center',
        allignText: 'center',
        justifyContent: 'center',
        top: hp(1.1),
    },
    modalContainer: {
        height: hp(65),
        width: hp(40),
        allignText: 'center',
        justifyContent: 'center',
        alignSelf: 'center',
        top: hp(22.5),
        borderRadius: 10,
        backgroundColor: '#759ee5',
    },
    uploadImage: {
        alignContent: 'center',
        alignItems: 'center',
        justifyContent: 'center',
        left: hp(1),
        marginTop: hp(2),
        top: hp(24),
        backgroundColor: '#ffffff',
        padding: hp(2.5),
        width: wp(35),
        borderRadius: hp(5),
    },
    uploadText: {
        color: '#023CAA',
        fontFamily: "GillSans-Light",
        fontSize: hp(1.8),
        textAlign: 'center',
        fontWeight: '500'
    },
    postButton: {
        alignContent: 'center',
        alignItems: 'center',
        justifyContent: 'center',
        left: hp(22),
        marginTop: hp(2),
        top: hp(15),
        backgroundColor: '#ffffff',
        padding: hp(2.5),
        width: wp(35),
        borderRadius: hp(5),
    },
    closeModal: {
        alignContent: 'center',
        alignItems: 'center',
        justifyContent: 'center',
        left: hp(12),
        marginTop: hp(2),
        top: hp(15),
        backgroundColor: '#ff0000',
        padding: hp(2.5),
        width: wp(35),
        borderRadius: hp(5),
    },
    deleteText: {
        color: '#ffffff',
        fontFamily: "GillSans-Light",
        fontSize: hp(1.8),
        textAlign: 'center',
        fontWeight: '500'
    },
    reviewTextInput: {
        lineHeight: hp(2),
        backgroundColor: '#ffffff',
        height: hp(15),
        width: hp(37.5),
        left: hp(1.25),
        borderRadius: 5,
        padding: hp(1),
        fontFamily: "GillSans-Light",
        fontSize: hp(2),
        textAlign: 'left',
        fontWeight: '500',
        top: hp(12),
    },
    aboveTextWrapper: {
        width: hp(6),
        height: hp(6),
        top: hp(-5.5),
        left: hp(1),
        borderRadius: hp(5),
        marginBottom: hp(-15),
        marginVertical: hp(1),
        backgroundColor: '#407eea',
    },
    scaleInitials: {
        fontFamily: "GillSans-Light",
        fontWeight: '500',
        fontSize: hp(2.25),
        alignSelf: 'center',
        allignText: 'center',
        justifyContent: 'center',
        top: hp(1.5),
        color : '#ffffff',
    },
    scaleUsername: {
        fontFamily: "GillSans-Light",
        fontWeight: '500',
        fontSize: hp(2.25),
        alignSelf: 'center',
        allignText: 'center',
        justifyContent: 'center',
        width: hp(20),
        top: hp(-1.25),
        left: hp(14),
    },
    seperateComp: {
        borderBottomColor: 'black',
        borderBottomWidth: StyleSheet.hairlineWidth,
        top: hp(10),
    },
    modalButtonContainer: {
        top: hp(-11),
    },
    base64Image: {
        width: hp(37.5),
        height: hp(20),
        alignSelf: 'center',
        top: hp(13),
        borderRadius: hp(1),
    }
});